services:
  type-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-6001}
    container_name: type-app
    env_file:
      - .env
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - .:/app
    command: /entrypoint.sh
    restart: unless-stopped