services:
  type-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-6001}
    container_name: type-app
    env_file:
      - .env
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    command: /entrypoint.sh
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: type-postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: