"""Initial migration

Revision ID: 339e81471694
Revises: 
Create Date: 2025-11-03 14:22:35.661159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339e81471694'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('paronym_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strike', sa.Boolean(), nullable=True),
    sa.Column('notification', sa.Boolean(), nullable=True),
    sa.Column('notification_time', sa.Time(), nullable=False),
    sa.Column('day_results', sa.Boolean(), nullable=False),
    sa.Column('day_results_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('paronym',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['paronym_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('explanation', sa.String(length=2048), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('mistake', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sentence', sa.String(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('word_tags', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['paronym.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sentence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence')
    op.drop_table('word')
    op.drop_table('paronym')
    op.drop_table('settings')
    op.drop_table('paronym_group')
    op.drop_table('category')
    op.drop_table('action')
    # ### end Alembic commands ###
