"""Refactor; User table

Revision ID: 5e4deff10513
Revises: 339e81471694
Create Date: 2025-11-04 15:50:50.389588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e4deff10513'
down_revision: Union[str, None] = '339e81471694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    op.alter_column('action', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('action', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('action', 'word_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('action', 'action',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('action', 'datetime',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.create_index(op.f('ix_action_user_id'), 'action', ['user_id'], unique=False)
    op.create_index(op.f('ix_action_word_id'), 'action', ['word_id'], unique=False)
    # Foreign keys будут добавлены после миграции данных
    op.alter_column('category', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('category', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.drop_index('idx_16470_sqlite_autoindex_category_1', table_name='category')
    op.create_unique_constraint(None, 'category', ['name'])
    op.alter_column('paronym', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('paronym', 'word',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('paronym', 'group_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_index('idx_16489_sqlite_autoindex_paronym_1', table_name='paronym')
    op.create_unique_constraint(None, 'paronym', ['word'])
    op.alter_column('paronym_group', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sentence', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sentence', 'sentence',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('sentence', 'word_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('sentence', 'word_tags',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_16494_sqlite_autoindex_sentence_1', table_name='sentence')
    op.create_unique_constraint(None, 'sentence', ['sentence'])
    # Изменения settings будут выполнены после миграции данных
    op.alter_column('settings', 'strike',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('settings', 'notification',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('settings', 'notification_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('settings', 'day_results',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('settings', 'day_results_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # Добавляем колонки как nullable сначала
    op.add_column('word', sa.Column('missing_part_index', sa.Integer(), nullable=True))
    op.add_column('word', sa.Column('right_answer', sa.String(length=128), nullable=True))
    op.add_column('word', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('word', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Заполняем данные для новых колонок
    connection = op.get_bind()
    
    # 1. Обработка слов: удаляем подчеркивания и находим missing_part_index
    import json
    
    words_result = connection.execute(sa.text("SELECT id, word, answers FROM word ORDER BY id"))
    processed_words = {}
    words_to_delete = []
    
    for row in words_result:
        word_id, original_word, answers_json = row
        
        # Находим позицию первого подчеркивания
        missing_index = original_word.find('_')
        
        # Удаляем все подчеркивания из слова
        cleaned_word = original_word.replace('_', '')
        
        # Получаем первый ответ из JSON массива
        try:
            answers = json.loads(answers_json) if isinstance(answers_json, str) else answers_json
            right_answer = answers[0] if answers and len(answers) > 0 else ""
        except (json.JSONDecodeError, IndexError, TypeError):
            right_answer = ""
        
        # Проверяем на дубликаты
        if cleaned_word in processed_words:
            # Это дубликат, удаляем его и переносим связанные данные
            original_word_id = processed_words[cleaned_word]
            
            # Переносим действия пользователей
            connection.execute(sa.text("""
                UPDATE action SET word_id = :original_id WHERE word_id = :duplicate_id
            """), {'original_id': original_word_id, 'duplicate_id': word_id})
            
            # Переносим предложения
            connection.execute(sa.text("""
                UPDATE sentence SET word_id = :original_id WHERE word_id = :duplicate_id
            """), {'original_id': original_word_id, 'duplicate_id': word_id})
            
            # Помечаем для удаления
            words_to_delete.append(word_id)
        else:
            # Это первое вхождение слова, обновляем его
            connection.execute(sa.text("""
                UPDATE word 
                SET word = :cleaned_word, 
                    missing_part_index = :missing_index,
                    right_answer = :right_answer,
                    created_at = CURRENT_TIMESTAMP,
                    updated_at = CURRENT_TIMESTAMP
                WHERE id = :word_id
            """), {
                'cleaned_word': cleaned_word,
                'missing_index': missing_index,
                'right_answer': right_answer,
                'word_id': word_id
            })
            processed_words[cleaned_word] = word_id
    
    # Удаляем дубликаты
    for word_id in words_to_delete:
        connection.execute(sa.text("DELETE FROM word WHERE id = :word_id"), {'word_id': word_id})
    
    # 2. Создаем временную таблицу для маппинга старых и новых ID пользователей
    op.execute("""
        CREATE TEMPORARY TABLE user_id_mapping (
            old_user_id BIGINT,
            new_user_id INTEGER
        )
    """)
    
    # 3. Переносим данные пользователей из action и settings в новую таблицу user
    # Получаем уникальных пользователей из action и settings
    connection.execute(sa.text("""
        WITH all_users AS (
            SELECT user_id as telegram_id, MIN(datetime) as created_at
            FROM action
            WHERE user_id IS NOT NULL
            GROUP BY user_id
            
            UNION
            
            SELECT user_id as telegram_id, CURRENT_TIMESTAMP as created_at
            FROM settings
            WHERE user_id IS NOT NULL
            AND user_id NOT IN (SELECT DISTINCT user_id FROM action WHERE user_id IS NOT NULL)
        )
        INSERT INTO "user" (telegram_id, created_at)
        SELECT telegram_id, MIN(created_at) as created_at
        FROM all_users
        GROUP BY telegram_id
    """))
    
    # 4. Заполняем маппинг старых и новых ID
    user_mapping_result = connection.execute(sa.text("""
        SELECT telegram_id, id FROM "user"
    """))
    
    for row in user_mapping_result:
        telegram_id, new_id = row
        connection.execute(sa.text("""
            INSERT INTO user_id_mapping (old_user_id, new_user_id)
            VALUES (:old_id, :new_id)
        """), {'old_id': telegram_id, 'new_id': new_id})
    
    # 5. Обновляем user_id в таблице action, используя маппинг
    connection.execute(sa.text("""
        UPDATE action 
        SET user_id = mapping.new_user_id
        FROM user_id_mapping mapping
        WHERE action.user_id = mapping.old_user_id
    """))
    
    # 6. Обновляем user_id в таблице settings, используя маппинг
    connection.execute(sa.text("""
        UPDATE settings 
        SET user_id = mapping.new_user_id
        FROM user_id_mapping mapping
        WHERE settings.user_id = mapping.old_user_id
    """))
    
    # Теперь делаем колонки NOT NULL
    op.alter_column('word', 'missing_part_index', nullable=False)
    op.alter_column('word', 'right_answer', nullable=False)
    
    # Добавляем уникальное ограничение на word после обработки данных
    op.create_unique_constraint(None, 'word', ['word'])
    
    # Очищаем недопустимые ссылки перед созданием foreign keys
    # Удаляем слова с несуществующими category_id
    connection.execute(sa.text("""
        DELETE FROM word 
        WHERE category_id NOT IN (SELECT id FROM category)
    """))
    
    # Добавляем foreign keys после миграции данных
    op.create_foreign_key(None, 'action', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'action', 'word', ['word_id'], ['id'])
    op.create_foreign_key(None, 'settings', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'word', 'category', ['category_id'], ['id'])
    op.alter_column('word', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('word', 'word',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('word', 'explanation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('word', 'answers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('word', 'task_number',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('word', 'category_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_index('idx_16484_sqlite_autoindex_word_1', table_name='word')
    # Уникальное ограничение и foreign key будут добавлены после обработки данных
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.drop_constraint(None, 'word', type_='unique')
    op.create_index('idx_16484_sqlite_autoindex_word_1', 'word', ['word'], unique=True)
    op.alter_column('word', 'category_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('word', 'task_number',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('word', 'answers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('word', 'explanation',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('word', 'word',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('word', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('word', 'updated_at')
    op.drop_column('word', 'created_at')
    op.drop_column('word', 'right_answer')
    op.drop_column('word', 'missing_part_index')
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.alter_column('settings', 'day_results_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('settings', 'day_results',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('settings', 'notification_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('settings', 'notification',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('settings', 'strike',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('settings', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'sentence', type_='unique')
    op.create_index('idx_16494_sqlite_autoindex_sentence_1', 'sentence', ['sentence'], unique=True)
    op.alter_column('sentence', 'word_tags',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sentence', 'word_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('sentence', 'sentence',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('sentence', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('paronym_group', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'paronym', type_='unique')
    op.create_index('idx_16489_sqlite_autoindex_paronym_1', 'paronym', ['word'], unique=True)
    op.alter_column('paronym', 'group_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('paronym', 'word',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('paronym', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'category', type_='unique')
    op.create_index('idx_16470_sqlite_autoindex_category_1', 'category', ['name'], unique=True)
    op.alter_column('category', 'name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('category', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'action', type_='foreignkey')
    op.drop_constraint(None, 'action', type_='foreignkey')
    op.drop_index(op.f('ix_action_word_id'), table_name='action')
    op.drop_index(op.f('ix_action_user_id'), table_name='action')
    op.alter_column('action', 'datetime',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('action', 'action',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('action', 'word_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('action', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('action', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
