"""Add UserWordStat and WordGlobalStat models

Revision ID: 83a4a9be2d82
Revises: 5e4deff10513
Create Date: 2025-11-08 08:47:37.376652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a4a9be2d82'
down_revision: Union[str, None] = '5e4deff10513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_word_stat',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('wrong_count', sa.Integer(), nullable=True),
    sa.Column('skip_count', sa.Integer(), nullable=True),
    sa.Column('success_streak', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_action', sa.Integer(), nullable=True),
    sa.Column('time_score', sa.Float(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'word_id')
    )
    op.create_index(op.f('ix_user_word_stat_difficulty_score'), 'user_word_stat', ['difficulty_score'], unique=False)
    op.create_index(op.f('ix_user_word_stat_time_score'), 'user_word_stat', ['time_score'], unique=False)
    op.create_table('word_global_stat',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('wrong_count', sa.Integer(), nullable=True),
    sa.Column('skip_count', sa.Integer(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_index(op.f('ix_word_global_stat_difficulty_score'), 'word_global_stat', ['difficulty_score'], unique=False)
    op.alter_column('settings', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('word', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('settings', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_word_global_stat_difficulty_score'), table_name='word_global_stat')
    op.drop_table('word_global_stat')
    op.drop_index(op.f('ix_user_word_stat_time_score'), table_name='user_word_stat')
    op.drop_index(op.f('ix_user_word_stat_difficulty_score'), table_name='user_word_stat')
    op.drop_table('user_word_stat')
    # ### end Alembic commands ###
